datasets:
  train:
    mode: cifar10
    phase: train
    dataroot: /mnt/disk4/baodq/comparision_ssl/datasets/cifar10_images
    batch_size: 128
    n_workers: 4

  val:
    mode: cifar10
    phase: val
    dataroot: /mnt/disk4/baodq/comparision_ssl/datasets/cifar10_images
    batch_size: 1024
    n_workers: 4

  test:
    mode: cifar10
    phase: test
    dataroot: /mnt/disk4/baodq/comparision_ssl/datasets/cifar10_images
    batch_size: 1024
    n_workers: 4

  