import math
import torch
import torch.nn as nn
from einops import rearrange
import numpy as np

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def apply_masks(x, masks):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param masks: list of tensors containing indices of patches in [N] to keep
    """
    all_x = []
    for m in masks:
        mask_keep = m.unsqueeze(-1).repeat(1, 1, x.size(-1))
        all_x += [torch.gather(x, dim=1, index=mask_keep)]
    return torch.cat(all_x, dim=0)


def repeat_interleave_batch(x, B, repeat):
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x

def get_2d_sincos_pos_embed(embed_dim, grid_size, cls_token=False):
    """
    grid_size: int of the grid height and width
    return:
    pos_embed: [grid_size*grid_size, embed_dim] or [1+grid_size*grid_size, embed_dim] (w/ or w/o cls_token)
    """
    grid_h = np.arange(grid_size, dtype=float)
    grid_w = np.arange(grid_size, dtype=float)
    grid = np.meshgrid(grid_w, grid_h)  # here w goes first
    grid = np.stack(grid, axis=0)

    grid = grid.reshape([2, 1, grid_size, grid_size])
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
    if cls_token:
        pos_embed = np.concatenate([np.zeros([1, embed_dim]), pos_embed], axis=0)
    return pos_embed


def get_2d_sincos_pos_embed_from_grid(embed_dim, grid):
    assert embed_dim % 2 == 0

    # use half of dimensions to encode grid_h
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)

    emb = np.concatenate([emb_h, emb_w], axis=1)  # (H*W, D)
    return emb


def get_1d_sincos_pos_embed(embed_dim, grid_size, cls_token=False):
    """
    grid_size: int of the grid length
    return:
    pos_embed: [grid_size, embed_dim] or [1+grid_size, embed_dim] (w/ or w/o cls_token)
    """
    grid = np.arange(grid_size, dtype=float)
    pos_embed = get_1d_sincos_pos_embed_from_grid(embed_dim, grid)
    if cls_token:
        pos_embed = np.concatenate([np.zeros([1, embed_dim]), pos_embed], axis=0)
    return pos_embed


def get_1d_sincos_pos_embed_from_grid(embed_dim, pos):
    """
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,)
    out: (M, D)
    """
    assert embed_dim % 2 == 0
    omega = np.arange(embed_dim // 2, dtype=float)
    omega /= embed_dim / 2.
    omega = 1. / 10000**omega   # (D/2,)

    pos = pos.reshape(-1)   # (M,)
    out = np.einsum('m,d->md', pos, omega)   # (M, D/2), outer product

    emb_sin = np.sin(out)  # (M, D/2)
    emb_cos = np.cos(out)  # (M, D/2)

    emb = np.concatenate([emb_sin, emb_cos], axis=1)  # (M, D)
    return emb

def drop_path(x, drop_prob: float = 0., training: bool = False):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=0.):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x, attn


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = MLP(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x, return_attention=False):
        y, attn = self.attn(self.norm1(x))
        if return_attention:
            return attn
        x = x + self.drop_path(y)
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class PatchEmbed(nn.Module):
    """ Image to Patch Embedding
    """
    def __init__(self, img_size=224, patch_size=16, in_chans=3, embed_dim=768):
        super().__init__()
        num_patches = (img_size // patch_size) * (img_size // patch_size)
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches

        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)

    def forward(self, x):
        B, C, H, W = x.shape
        x = self.proj(x).flatten(2).transpose(1, 2)
        return x


class ConvEmbed(nn.Module):
    """
    3x3 Convolution stems for ViT following ViTC models
    """

    def __init__(self, channels, strides, img_size=224, in_chans=3, batch_norm=True):
        super().__init__()
        # Build the stems
        stem = []
        channels = [in_chans] + channels
        for i in range(len(channels) - 2):
            stem += [nn.Conv2d(channels[i], channels[i+1], kernel_size=3,
                               stride=strides[i], padding=1, bias=(not batch_norm))]
            if batch_norm:
                stem += [nn.BatchNorm2d(channels[i+1])]
            stem += [nn.ReLU(inplace=True)]
        stem += [nn.Conv2d(channels[-2], channels[-1], kernel_size=1, stride=strides[-1])]
        self.stem = nn.Sequential(*stem)

        # Comptute the number of patches
        stride_prod = int(np.prod(strides))
        self.num_patches = (img_size[0] // stride_prod)**2

    def forward(self, x):
        p = self.stem(x)
        return p.flatten(2).transpose(1, 2)

class MobileNetEncoder(nn.Module):
    """MobileNet backbone encoder for I-JEPA"""
    def __init__(self, c_in=3, embed_dim=512, pretrained=False):
        super().__init__()
        def conv_bn(inp, oup, stride):
            return nn.Sequential(
                nn.Conv2d(inp, oup, 3, stride, padding=1, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True)
            )
        
        def conv_dw(inp, oup, stride):
            return nn.Sequential(
                # Depthwise
                nn.Conv2d(inp, inp, 3, stride, padding=1, groups=inp, bias=False),
                nn.BatchNorm2d(inp),
                nn.ReLU(inplace=True),
                # Pointwise
                nn.Conv2d(inp, oup, 1, 1, 0, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True),
            )
        self.features = nn.Sequential(
            conv_bn(c_in, 32, stride=1),        # 32×32×3 → 32×32×32
            conv_dw( 32,  64, 1),            # 32×32×32 → 32×32×64
            conv_dw( 64, 128, 2),            # → 16×16×128
            conv_dw(128, 128, 1),          # → 16×16×128

            #Repeat 5 blocks with 128 channels
            conv_dw(128, 128, 1),
            conv_dw(128, 128, 1),
            conv_dw(128, 128, 1),
            conv_dw(128, 128, 1),
            conv_dw(128, 128, 1),
        )
        self.embed_dim = embed_dim
        self.feature_channels = 128
        self.spatial_size = 16
        self.num_patches = 256 #16x16

        # Project from 1024 to embed_dim if different
        if embed_dim != self.feature_channels:
            self.projection = nn.Linear(self.feature_channels, embed_dim)
        else:
            self.projection = nn.Identity()
        
        #Position embedding
        self.pos_embed = nn.Parameter(torch.zeros(1, self.num_patches, embed_dim), requires_grad=False)  # fixed sin-cos embedding
        pos_embed = get_2d_sincos_pos_embed(self.pos_embed.shape[-1], self.spatial_size, cls_token=False)
        self.pos_embed.data.copy_(torch.from_numpy(pos_embed).float().unsqueeze(0))

        # Layer normalization
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x, masks=None):
        """
        Args:
            x: input images [B, C, H, W]
            masks: optional list of masks for patches
        Returns:
            features: [B, N, D] where N is number of patches (spatial locations)
        """
        # Get features from MobileNet (before pooling)
        # We'll stop before the final pooling layer
        x = self.features(x)  # [B, C, H, W]

        B, C, H, W = x.shape

        # Reshape to [B, N, C]
        x = rearrange(x, "b c h w -> b (h w) c")  # [B, N, 512]

        # Project to embed_dim
        x = self.projection(x)  # [B, N, embed_dim]
        x = x + self.pos_embed

        # Apply masks if provided
        if masks is not None:
            if not isinstance(masks, list):
                masks = [masks]
            x = apply_masks(x, masks)

        # Apply normalization
        x = self.norm(x)

        return x

    def get_num_patches(self, img_size):
        """Calculate number of patches for given image size"""
        return self.num_patches

class MobileNet_Predictor(nn.Module):
    def __init__(self, 
                num_patches:int = 256,
                predictor_embed_dim:int = 256,
                embed_dim:int = 512,
                depth = 8,
                num_heads = 12,
                mlp_ratio=4.0,
                qkv_bias=True,
                qk_scale=None,
                drop_rate=0.0,
                attn_drop_rate=0.0,
                drop_path_rate=0.0,
                norm_layer=nn.LayerNorm,
                init_std=0.02,
                **kwargs
                ):

        super().__init__()
        self.predictor_embed = nn.Linear(embed_dim, predictor_embed_dim, bias = True)
        self.mask_token = nn.Parameter(torch.zeros(1, 1, predictor_embed_dim))
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.predictor_pos_embed = nn.Parameter(torch.zeros(1, num_patches, predictor_embed_dim), requires_grad=False)  # fixed sin-cos embedding
        predictor_pos_embed = get_2d_sincos_pos_embed(self.predictor_pos_embed.shape[-1],
                                                      int(num_patches**.5),
                                                      cls_token=False)
        self.predictor_pos_embed.data.copy_(torch.from_numpy(predictor_pos_embed).float().unsqueeze(0))
        # --
        self.predictor_blocks = nn.ModuleList([
            Block(
                dim=predictor_embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])
        self.predictor_norm = norm_layer(predictor_embed_dim)
        self.predictor_proj = nn.Linear(predictor_embed_dim, embed_dim, bias=True)
        # ------
        self.init_std = init_std
        trunc_normal_(self.mask_token, std=self.init_std)
        self.apply(self._init_weights)
        self.fix_init_weight()

    def fix_init_weight(self):
        def rescale(param, layer_id):
            param.div_(math.sqrt(2.0 * layer_id))

        for layer_id, layer in enumerate(self.predictor_blocks):
            rescale(layer.attn.proj.weight.data, layer_id + 1)
            rescale(layer.mlp.fc2.weight.data, layer_id + 1)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=self.init_std)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            trunc_normal_(m.weight, std=self.init_std)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
    def forward(self, x, masks_x, masks):
        assert (masks is not None) and (masks_x is not None), 'Cannot run predictor without mask indices'

        if not isinstance(masks_x, list):
            masks_x = [masks_x]

        if not isinstance(masks, list):
            masks = [masks]

        # -- Batch Size
        B = len(x) // len(masks_x)

        # -- map from encoder-dim to pedictor-dim
        x = self.predictor_embed(x)

        # -- add positional embedding to x tokens
        x_pos_embed = self.predictor_pos_embed.repeat(B, 1, 1)
        x += apply_masks(x_pos_embed, masks_x)

        _, N_ctxt, D = x.shape

        # -- concat mask tokens to x
        pos_embs = self.predictor_pos_embed.repeat(B, 1, 1)
        pos_embs = apply_masks(pos_embs, masks)
        pos_embs = repeat_interleave_batch(pos_embs, B, repeat=len(masks_x))
        # --
        pred_tokens = self.mask_token.repeat(pos_embs.size(0), pos_embs.size(1), 1)
        # --
        pred_tokens += pos_embs
        x = x.repeat(len(masks), 1, 1)
        x = torch.cat([x, pred_tokens], dim=1)

        # -- fwd prop
        for blk in self.predictor_blocks:
            x = blk(x)
        x = self.predictor_norm(x)

        # -- return preds for mask tokens
        x = x[:, N_ctxt:]
        x = self.predictor_proj(x)

        return x

class MobileNet_JEPA(nn.Module):
    """Full I-JEPA model with MobileNet backbone and EMA target encoder"""
    def __init__(self, 
                 c_in=3, 
                 embed_dim=512, 
                 predictor_embed_dim=256,
                 num_patches=256,
                 predictor_depth=6,
                 predictor_num_heads=8,
                 momentum=0.996):
        super().__init__()
        
        # Context encoder (trainable)
        self.context_encoder = MobileNetEncoder(c_in, embed_dim)
        
        # Target encoder (EMA updated, not trainable)
        self.target_encoder = MobileNetEncoder(c_in, embed_dim)
        
        # Predictor
        self.predictor = MobileNet_Predictor(
            num_patches=num_patches,
            predictor_embed_dim=predictor_embed_dim,
            embed_dim=embed_dim,
            depth=predictor_depth,
            num_heads=predictor_num_heads
        )
        
        # EMA momentum for target encoder updates
        self.momentum = momentum
        
        # Initialize target encoder with context encoder weights
        self._init_target_encoder()
        
    def _init_target_encoder(self):
        """Initialize target encoder with same weights as context encoder"""
        for param_c, param_t in zip(
            self.context_encoder.parameters(),
            self.target_encoder.parameters()
        ):
            param_t.data.copy_(param_c.data)
            param_t.requires_grad = False  # Target encoder is not trained directly
    
    @torch.no_grad()
    def update_target_encoder(self, momentum=None):
        """
        Exponential Moving Average (EMA) update of target encoder
        
        Args:
            momentum: EMA momentum (default: use self.momentum)
        """
        if momentum is None:
            momentum = self.momentum
            
        for param_c, param_t in zip(
            self.context_encoder.parameters(),
            self.target_encoder.parameters()
        ):
            param_t.data.mul_(momentum).add_(param_c.data, alpha=1.0 - momentum)
    
    def forward(self, x, context_mask, target_mask):
        """
        Forward pass for I-JEPA training
        
        Args:
            x: input images [B, C, H, W]
            context_mask: indices of patches to use as context [B, N_context] or list
            target_mask: indices of patches to predict [B, N_target] or list
            
        Returns:
            predictions: predicted features for target patches [B, N_target, D]
            target_features: actual features from target encoder [B, N_target, D]
        """
        # Get context representations (trainable encoder)
        context_features = self.context_encoder(x, masks=[context_mask])
        
        # Get target representations (EMA encoder, no gradients)
        with torch.no_grad():
            target_features = self.target_encoder(x, masks=[target_mask])
        
        # Predict target features from context
        predictions = self.predictor(
            context_features,
            masks_x=[context_mask],
            masks=[target_mask]
        )
        
        return predictions, target_features
    
    def get_context_encoder(self):
        """Return the trainable context encoder for downstream tasks"""
        return self.context_encoder
if __name__ == "__main__":
    print("="*60)
    print("Testing Full I-JEPA Model with EMA Target Encoder")
    print("="*60)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Create full I-JEPA model
    model = MobileNet_JEPA(
        c_in=3,
        embed_dim=512,
        predictor_embed_dim=256,
        num_patches=256,
        predictor_depth=6,
        predictor_num_heads=8,
        momentum=0.996
    ).to(device)
    
    print(f"Context Encoder parameters: {sum(p.numel() for p in model.context_encoder.parameters() if p.requires_grad) / 1_000_000:.2f}M")
    print(f"Target Encoder parameters: {sum(p.numel() for p in model.target_encoder.parameters()) / 1_000_000:.2f}M (frozen)")
    print(f"Predictor parameters: {sum(p.numel() for p in model.predictor.parameters() if p.requires_grad) / 1_000_000:.2f}M")
    print(f"Total trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad) / 1_000_000:.2f}M")
    
    # Batch of input images
    batch_size = 128
    images = torch.randn(batch_size, 3, 32, 32).to(device)
    print(f"\nInput images shape: {images.shape}")
    
    # Create masks
    num_patches = 256
    num_context = int(num_patches * 0.7)  # Keep 70% as context (179 patches)
    num_target = int(num_patches * 0.3)   # Predict 30% (77 patches)
    
    # Random masks for each image in batch
    context_mask = torch.stack([torch.randperm(num_patches)[:num_context] for _ in range(batch_size)]).to(device)
    target_mask = torch.stack([torch.randperm(num_patches)[:num_target] for _ in range(batch_size)]).to(device)
    
    print(f"\nContext patches: {num_context}")
    print(f"Target patches: {num_target}")
    print(f"Context mask shape: {context_mask.shape}")
    print(f"Target mask shape: {target_mask.shape}")
    
    # Forward pass
    model.train()
    predictions, target_features = model(images, context_mask, target_mask)
    
    print(f"\nPredictions shape: {predictions.shape}")  # [128, 77, 512]
    print(f"Target features shape: {target_features.shape}")  # [128, 77, 512]
    
    # Compute loss (smooth L1 loss as in I-JEPA paper)
    loss = nn.SmoothL1Loss()(predictions, target_features)
    print(f"\nLoss: {loss.item():.6f}")
    
    # Simulate training step
    print("\n" + "="*60)
    print("Simulating Training Step")
    print("="*60)
    
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)
    
    # Backward pass
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    
    # Update target encoder with EMA
    model.update_target_encoder()
    print("✓ Target encoder updated with EMA")
    
    # Verify that context and target encoders are different after update
    context_param = next(model.context_encoder.parameters())
    target_param = next(model.target_encoder.parameters())
    param_diff = (context_param - target_param).abs().mean().item()
    print(f"✓ Parameter difference between encoders: {param_diff:.6f}")
    
    print("\n" + "="*60)
    print("Summary")
    print("="*60)
    print(f"✓ Input: {images.shape}")
    print(f"✓ Predictions: {predictions.shape}")
    print(f"✓ Target features: {target_features.shape}")
    print(f"✓ Loss: {loss.item():.6f}")
    print(f"✓ EMA target encoder working correctly")
    print("\n I-JEPA model tested successfullly!")