model: "resnet34_dino"
pretrain_path: "/mnt/disk4/baodq/Self-Supervised-Learning-comparisons/checkpoints/dino/dino_resnet34_final.pth"
out_nc: 10
seed: 42
save_checkpoint_path: "/mnt/disk4/baodq/Self-Supervised-Learning-comparisons/src/checkpoints/dino/resnet34_cifar10/"

is_train: true
is_test: true

hyperparameters:
  lr: 0.01
  epochs: 150
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.999
  eta_min: 0.0001
  seed: 42

  validate_mode: epoch # options: step / epoch
  validate_step_freq: 100
  validate_epochs_freq: 1


datasets:
  train:
    mode: cifar10
    phase: train
    dataroot: ./datasets/cifar10_images
    batch_size: 128
    n_workers: 4

  val:
    mode: cifar10
    phase: val
    dataroot: ./datasets/cifar10_images
    batch_size: 1024
    n_workers: 4

  test:
    mode: cifar10
    phase: test
    dataroot: ./datasets/cifar10_images
    batch_size: 1024
    n_workers: 4